# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadster_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadstermember',
            options={'verbose_name_plural': 'roadster_members'},
        ),
        migrations.AlterModelTable(
            name='roadstermember',
            table='roadster_member',
        ),
    ]
