# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadster',
            options={'verbose_name_plural': 'roadsters'},
        ),
        migrations.AlterModelTable(
            name='roadster',
            table='roadster',
        ),
    ]
