# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'verbose_name_plural': 'loots'},
        ),
        migrations.AlterModelTable(
            name='loot',
            table='loot',
        ),
    ]
