# Generated by Django 5.1.2 on 2024-10-28 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bis_stuff', '0001_initial'),
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisstuff',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.stuff'),
        ),
    ]
