# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis_stuff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bisstuff',
            options={'verbose_name_plural': 'best_in_slot_stuffs'},
        ),
        migrations.AlterModelTable(
            name='bisstuff',
            table='best_in_slot_stuff',
        ),
    ]
