# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bis',
            options={'verbose_name_plural': 'best_in_slots'},
        ),
        migrations.AlterModelTable(
            name='bis',
            table='best_in_slot',
        ),
    ]
