# Generated by Django 5.1.2 on 2024-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_combat_type_alter_member_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_privileged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
