# Generated by Django 5.1.2 on 2024-10-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_is_privileged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
