# Generated by Django 5.1.2 on 2024-10-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_options_alter_member_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='added_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='removed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
