# Generated by Django 5.1.2 on 2024-10-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boss', '0001_initial'),
        ('loot_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_activate', models.BooleanField(blank=True, default=True, null=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss.boss')),
                ('loot_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot_type.loottype')),
            ],
        ),
    ]
