# Generated by Django 5.1.2 on 2024-10-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_type', '0001_initial'),
        ('grade', '0001_initial'),
        ('member', '0002_member_combat_type_member_grade_member_weapon'),
        ('weapon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='combat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='combat_type.combattype'),
        ),
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.grade'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weapon.weapon'),
        ),
    ]
