# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberdistribution',
            options={'verbose_name_plural': 'member_distributions'},
        ),
        migrations.AlterModelTable(
            name='memberdistribution',
            table='member_distribution',
        ),
    ]
