# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combattype',
            options={'verbose_name_plural': 'combat_types'},
        ),
        migrations.AlterModelTable(
            name='combattype',
            table='combat_type',
        ),
    ]
