# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loottype',
            options={'verbose_name_plural': 'loot_types'},
        ),
        migrations.AlterModelTable(
            name='loottype',
            table='loot_type',
        ),
    ]
