# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuff',
            options={'verbose_name_plural': 'stuffs'},
        ),
        migrations.AlterModelTable(
            name='stuff',
            table='stuff',
        ),
    ]
