# Generated by Django 5.1.2 on 2024-10-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distribution', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_needed', models.BooleanField(blank=True, default=True, null=True)),
                ('contribution_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('active_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('discord_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('total_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('dice_result', models.IntegerField(blank=True, null=True)),
                ('total_result', models.IntegerField(blank=True, null=True)),
                ('has_looted', models.BooleanField(blank=True, default=False, null=True)),
                ('date_loot', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_activate', models.BooleanField(blank=True, default=True, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.distribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
    ]
